suppressPackageStartupMessages({library(ggplot2);library(dplyr);library(tidyr);library(readr);library(scales);library(ggrepel);library(patchwork)})
args=commandArgs(trailingOnly=TRUE); indir=args[1]; outdir=args[2]; dir.create(outdir,recursive=TRUE,showWarnings=FALSE)
cell=read_csv(file.path(indir,'cell_metrics.csv'),show_col_types=FALSE); con=read_csv(file.path(indir,'contrasts.csv'),show_col_types=FALSE); oe=read_csv(file.path(indir,'outcome_effects.csv'),show_col_types=FALSE); joint=read_csv(file.path(indir,'joint_metrics.csv'),show_col_types=FALSE); patt=read_csv(file.path(indir,'pattern_distribution.csv'),show_col_types=FALSE); age=read_csv(file.path(indir,'age_reasoning_effects.csv'),show_col_types=FALSE); tails=read_csv(file.path(indir,'probability_tail.csv'),show_col_types=FALSE)
cols=c('Luna'='#6C5CE7','Claude'='#0984E3','Qwen'='#E17055','DeepSeek'='#00A67E','Human'='#2D3436','Logistic'='#7F8C8D','Gradient boost'='#636E72','Random forest'='#95A5A6')
base_theme=theme_minimal(base_size=11)+theme(plot.title=element_blank(),plot.subtitle=element_blank(),panel.grid.minor=element_blank(),panel.grid.major=element_line(linewidth=.25,color='grey88'),axis.title=element_text(size=10),axis.text=element_text(color='grey20'),legend.title=element_blank(),legend.position='bottom',strip.text=element_text(face='bold',size=9),plot.margin=margin(8,14,8,8))
savefig=function(p,n,w=7,h=4.6){ggsave(file.path(outdir,paste0(n,'.pdf')),p,width=w,height=h,device=cairo_pdf);ggsave(file.path(outdir,paste0(n,'.svg')),p,width=w,height=h);ggsave(file.path(outdir,paste0(n,'.png')),p,width=w,height=h,dpi=450)}
pretty_con=c(luna_rich_minus_thin='Luna',claude_rich_minus_thin='Claude',qwen_medium_minus_off='Qwen',deepseek_rich_high_minus_off='DeepSeek')
# 1 micro/macro map
m1=con%>%filter(contrast%in%names(pretty_con),metric%in%c('individual_brier','hard_prevalence_mae'))%>%select(contrast,metric,estimate)%>%pivot_wider(names_from=metric,values_from=estimate)%>%mutate(label=pretty_con[contrast],model=label,x=100*individual_brier,y=100*hard_prevalence_mae)
p1=ggplot(m1,aes(x,y,color=model))+geom_hline(yintercept=0,color='grey65',linewidth=.35)+geom_vline(xintercept=0,color='grey65',linewidth=.35)+geom_point(size=3.5)+geom_text_repel(aes(label=label),show.legend=FALSE,size=3.4,box.padding=.5,min.segment.length=0)+scale_color_manual(values=cols)+labs(x='Change in individual Brier (×100)',y='Change in hard population MAE (pp)')+base_theme+theme(legend.position='none')
savefig(p1,'fig01_micro_macro')
# 2 model-specific reasoning effects, four metrics with CI
r2=con%>%filter(contrast%in%c('qwen_medium_minus_off','deepseek_rich_high_minus_off'),metric%in%c('individual_brier','hard_accuracy','probability_prevalence_mae','hard_prevalence_mae'))%>%mutate(model=ifelse(grepl('qwen',contrast),'Qwen','DeepSeek'),metric=recode(metric,individual_brier='Brier ×100',hard_accuracy='Accuracy',probability_prevalence_mae='Probability MAE',hard_prevalence_mae='Hard MAE'),scale=ifelse(metric=='Brier ×100',100,100),estimate=estimate*scale,ci_low=ci_low*scale,ci_high=ci_high*scale)
p2=ggplot(r2,aes(estimate,model,color=model))+geom_vline(xintercept=0,color='grey60',linewidth=.35)+geom_errorbarh(aes(xmin=ci_low,xmax=ci_high),height=.18,linewidth=.65)+geom_point(size=2.8)+facet_wrap(~metric,scales='free_x',nrow=1)+scale_color_manual(values=cols)+labs(x='High reasoning − off',y=NULL)+base_theme+theme(legend.position='none')
savefig(p2,'fig02_reasoning_reversal',9.2,3.2)
# 3 DeepSeek factorial
f3=cell%>%filter(cell%in%c('deepseek_thin_off','deepseek_thin_high','deepseek_rich_off','deepseek_rich_high'))%>%mutate(persona=ifelse(grepl('thin',cell),'Thin','Rich'),reasoning=ifelse(grepl('high',cell),'High','Off'))%>%select(persona,reasoning,individual_brier,hard_prevalence_mae)%>%pivot_longer(c(individual_brier,hard_prevalence_mae),names_to='metric',values_to='value')%>%mutate(metric=recode(metric,individual_brier='Brier',hard_prevalence_mae='Hard population MAE'),value=ifelse(metric=='Hard population MAE',100*value,value))
p3=ggplot(f3,aes(factor(reasoning,levels=c('Off','High')),value,group=persona,color=persona))+geom_line(linewidth=1)+geom_point(size=3)+facet_wrap(~metric,scales='free_y',nrow=1)+scale_color_manual(values=c(Thin='#A29BFE',Rich='#00A67E'))+labs(x=NULL,y=NULL)+base_theme
savefig(p3,'fig03_deepseek_factorial',7.4,3.6)
# 4 age gradient
ag=age%>%filter(metric=='probability_prevalence_mae')%>%mutate(age_group=factor(age_group,levels=c('15-24','25-34','35-44','45-59','60+')),estimate=100*estimate,ci_low=100*ci_low,ci_high=100*ci_high)
p4=ggplot(ag,aes(age_group,estimate,group=model,color=model))+geom_hline(yintercept=0,color='grey55',linewidth=.4)+geom_ribbon(aes(ymin=ci_low,ymax=ci_high,fill=model),alpha=.09,color=NA)+geom_line(linewidth=.9)+geom_point(size=2.5)+scale_color_manual(values=cols)+scale_fill_manual(values=cols)+labs(x='Age',y='Reasoning effect on population MAE (pp)')+base_theme
savefig(p4,'fig04_age_gradient',7,4.2)
# 5 population fingerprint: top patterns by human plus salient phone-first
usecells=c('human','qwen_off','qwen_medium','deepseek_rich_off','deepseek_rich_high'); names2=c(human='Human',qwen_off='Qwen off',qwen_medium='Qwen medium',deepseek_rich_off='DeepSeek off',deepseek_rich_high='DeepSeek high')
top=patt%>%filter(cell=='human')%>%arrange(desc(share))%>%slice_head(n=10)%>%pull(pattern); top=unique(c('110111','110110',top))
h5=patt%>%filter(cell%in%usecells,pattern%in%top)%>%mutate(cell=factor(names2[cell],levels=unname(names2)),pattern=factor(pattern,levels=rev(top)))
p5=ggplot(h5,aes(cell,pattern,fill=share))+geom_tile(color='white',linewidth=.55)+geom_text(aes(label=ifelse(share>=.025,percent(share,accuracy=1),'')),size=2.8)+scale_fill_gradient(low='#F5F6FA',high='#2D3436',labels=percent)+labs(x=NULL,y='Response pattern')+base_theme+theme(legend.position='none',panel.grid=element_blank())
savefig(p5,'fig05_population_fingerprint',7.4,5)
# 6 fidelity landscape LLMs and supervised comparators
j6=joint%>%filter(cell!='human')%>%select(cell,joint_tv); c6=cell%>%left_join(j6,by='cell')%>%filter(!is.na(individual_brier),!is.na(joint_tv))%>%mutate(label=case_when(cell=='qwen_off'~'Qwen off',cell=='qwen_medium'~'Qwen medium',cell=='deepseek_rich_off'~'DeepSeek off',cell=='deepseek_rich_high'~'DeepSeek high',cell=='baseline_regularized_logistic'~'Logistic',cell=='baseline_gradient_boosting'~'Gradient boost',cell=='baseline_random_forest'~'Random forest',TRUE~NA_character_),family=ifelse(method_class=='LLM','LLM','Supervised'))%>%filter(!is.na(label))
p6=ggplot(c6,aes(individual_brier,joint_tv,shape=family))+geom_point(size=3.3,color='#2D3436')+geom_text_repel(aes(label=label),size=3.1,box.padding=.45,min.segment.length=0)+labs(x='Individual Brier',y='Joint TV distance',shape=NULL)+base_theme+theme(legend.position='bottom')
savefig(p6,'fig06_fidelity_landscape',6.8,4.8)
# 7 overconfidence paradox
d7=cell%>%filter(cell%in%c('deepseek_rich_off','deepseek_rich_high'))%>%select(cell,individual_brier,log_loss)%>%left_join(tails,by='cell')%>%mutate(condition=ifelse(grepl('high',cell),'High','Off'))%>%select(condition,individual_brier,log_loss,wrong_extreme_share)%>%pivot_longer(-condition,names_to='metric',values_to='value')%>%mutate(metric=recode(metric,individual_brier='Brier',log_loss='Log loss',wrong_extreme_share='Wrong extreme'),value=ifelse(metric=='Wrong extreme',100*value,value))
p7=ggplot(d7,aes(condition,value,group=1))+geom_line(color='grey70',linewidth=.8)+geom_point(size=3,color='#00A67E')+facet_wrap(~metric,scales='free_y',nrow=1)+labs(x=NULL,y=NULL)+base_theme+theme(legend.position='none')
savefig(p7,'fig07_overconfidence',7.6,3.2)
# 8 outcome-level effect heatmap
h8=oe%>%filter(contrast%in%c('qwen_medium_minus_off','deepseek_rich_high_minus_off'),metric%in%c('brier','probability_prevalence_abs_error','hard_prevalence_abs_error'))%>%mutate(model=ifelse(grepl('qwen',contrast),'Qwen','DeepSeek'),metric=recode(metric,brier='Brier',probability_prevalence_abs_error='Prob. MAE',hard_prevalence_abs_error='Hard MAE'),effect=100*effect,outcome=recode(outcome,mobile_ability='Mobile',mobile_3m='Mobile 3m',computer_ability='Computer',internet_ability='Internet',internet_3m='Internet 3m',copy_paste='Copy/paste'))
p8=ggplot(h8,aes(metric,outcome,fill=effect))+geom_tile(color='white',linewidth=.6)+geom_text(aes(label=sprintf('%+.1f',effect)),size=2.8)+facet_wrap(~model,nrow=1)+scale_fill_gradient2(low='#00A67E',mid='white',high='#D63031',midpoint=0)+labs(x=NULL,y=NULL)+base_theme+theme(legend.position='none',panel.grid=element_blank())
savefig(p8,'figS01_outcome_effects',7.6,4.6)
writeLines(c('fig01_micro_macro','fig02_reasoning_reversal','fig03_deepseek_factorial','fig04_age_gradient','fig05_population_fingerprint','fig06_fidelity_landscape','fig07_overconfidence','figS01_outcome_effects'),file.path(outdir,'FIGURE_INDEX.txt'))
