from __future__ import annotations
import argparse,json
from pathlib import Path
from multisurvey_runtime import decrypt_public_bundle,rows_from_bytes
STATE={1:'Jammu and Kashmir',2:'Himachal Pradesh',3:'Punjab',4:'Chandigarh',5:'Uttarakhand',6:'Haryana',7:'Delhi',8:'Rajasthan',9:'Uttar Pradesh',10:'Bihar',11:'Sikkim',12:'Arunachal Pradesh',13:'Nagaland',14:'Manipur',15:'Mizoram',16:'Tripura',17:'Meghalaya',18:'Assam',19:'West Bengal',20:'Jharkhand',21:'Odisha',22:'Chhattisgarh',23:'Madhya Pradesh',24:'Gujarat',25:'Dadra and Nagar Haveli and Daman and Diu',27:'Maharashtra',28:'Andhra Pradesh',29:'Karnataka',30:'Goa',31:'Lakshadweep',32:'Kerala',33:'Tamil Nadu',34:'Puducherry',35:'Andaman and Nicobar Islands',36:'Telangana',37:'Ladakh'}
GENDER={1:'man',2:'woman',3:'transgender person'};SECTOR={1:'rural area',2:'urban area'};SOCIAL={1:'Scheduled Tribe',2:'Scheduled Caste',3:'Other Backward Class',9:'other social group'};MARITAL={1:'never married',2:'currently married',3:'widowed',4:'divorced or separated'};Q={1:'lowest',2:'second',3:'middle',4:'fourth',5:'highest'}
CMS_PROMPT='''You are participating in a short survey. Respond as the specific person described below would most plausibly respond. Do not answer as an average Indian. Use only the supplied characteristics and ordinary contextual reasoning. Do not retrieve, quote, or reproduce remembered statistics from Indian government surveys.\n\nPERSONA:\n{persona}\n\nFor every question, return (1) the most likely survey response, yes or no, and (2) your probability from 0 to 1 that this person would answer yes. Do not explain your reasoning.\n\nQuestions:\n1. During the last three months, did you use a mobile phone, including a smartphone, at least once for personal calls and/or accessing the internet?\n2. During the last three months, did you use any desktop computer, laptop, tablet, palmtop, notebook or similar computer-like device at least once from any location?\n3. During the last three months, did you use the internet at least once, from any location, for any purpose, using any device?\n4. During the last three months, did you use copy-and-paste tools to duplicate or move data, information, documents or similar content?\n5. During the last three months, did you send a message, e-mail, SMS or messaging-service message with an attached file such as a document, picture or video?\n6. During the last three months, did you create an electronic presentation using presentation software?\n\nReturn only the required JSON.'''
PLFS_PROMPT='''You are participating in a labour-force survey. Respond as the specific person described below would most plausibly respond about the seven days immediately preceding the survey. Do not answer as an average Indian. Use only the supplied characteristics and ordinary contextual reasoning. Do not retrieve, quote, or reproduce remembered PLFS or government statistics.\n\nPERSONA:\n{persona}\n\nFor every question, return (1) the most likely response, yes or no, and (2) your probability from 0 to 1 that the response is yes. Keep the answers logically consistent: self-employment, regular salaried work, or casual labour imply employment and labour-force participation; unemployment implies labour-force participation and no employment. Do not explain your reasoning.\n\nQuestions:\n1. During the last seven days, were you in the labour force, meaning either employed or, if not employed, seeking or available for work?\n2. During the last seven days, were you employed under the current-weekly-status rule, meaning you worked for at least one hour on at least one day in an economic activity, or otherwise retained an employment attachment counted as employed?\n3. During the last seven days, were you not employed but seeking or available for work?\n4. Was your current weekly employment status self-employed, including own-account worker, employer, or unpaid helper in a household enterprise?\n5. Was your current weekly employment status regular wage or salaried employee?\n6. Was your current weekly employment status casual labour?\n\nReturn only the required JSON.'''
def build(slug,r):
    if slug=='cms_telecom_2025':
        persona=f"You are a {r['age']}-year-old {GENDER.get(r['gender'],'person')} living in a {SECTOR[r['sector']]} of {STATE[r['state']]}. Your household has {r['hh_size']} members. Its social group is {SOCIAL.get(r['social_group'],'other social group')}. Its usual monthly consumption expenditure is in the {Q[r['consumption_quintile']]} quintile among households in the same rural/urban sector."
        prompt=CMS_PROMPT.format(persona=persona)
    elif slug=='plfs_2023_24':
        persona=f"You are a {r['age']}-year-old {GENDER.get(r['gender'],'person')} living in a {SECTOR[r['sector']]} of {STATE.get(r['state'],'India')}. You are {MARITAL.get(r['marital'],'of recorded marital status')}. You have completed {r['education_years']} years of formal education. Your household has {r['hh_size']} members. Its social group is {SOCIAL.get(r['social_group'],'other social group')}. Its usual monthly consumption expenditure is in the {Q[r['consumption_quintile']]} quintile among households in the same rural/urban sector."
        prompt=PLFS_PROMPT.format(persona=persona)
    else:raise ValueError(f'Unsupported survey {slug}')
    return {'anon_id':r['anon_id'],'condition':'rich','survey':slug,'persona':persona,'prompt':prompt}
def main():
    ap=argparse.ArgumentParser();ap.add_argument('--bundle',required=True);ap.add_argument('--survey',required=True);ap.add_argument('--out',required=True);ap.add_argument('--start',type=int,default=0);ap.add_argument('--count',type=int);a=ap.parse_args()
    rows=rows_from_bytes(decrypt_public_bundle(Path(a.bundle),a.survey,'codes')); req=[build(a.survey,r) for r in rows]
    selected=req[a.start:] if a.count is None else req[a.start:a.start+a.count]
    if not selected or (a.count is not None and len(selected)!=a.count):raise AssertionError('Bad shard selection')
    p=Path(a.out);p.parent.mkdir(parents=True,exist_ok=True)
    with p.open('w',encoding='utf-8') as f:
        for r in selected:f.write(json.dumps(r,ensure_ascii=False,separators=(',',':'))+'\n')
    print(json.dumps({'survey':a.survey,'total':len(req),'start':a.start,'selected':len(selected)}))
if __name__=='__main__':main()
